### ISSUE TITLE
Error while running the code

### ISSUE THREAD

**Issue by Junaid199f** [marsggbo/hyperbox#33]
Hi! 
While running the run.py file i got this error.

D:\Codes\hyperbox-master\venv\lib\site-packages\hydra\_internal\defaults_list.py:251: UserWarning: In 'config.yaml': Defaults list is missing `_self_`. See https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
[2022-09-28 13:10:58] [INFO] [D:\Codes\hyperbox-master\hyperbox\utils\utils.py:99 (hyperbox.utils.utils)] Disabling python warnings! <config.ignore_warnings=True>
Error executing job with overrides: []
Traceback (most recent call last):
  File "D:\Codes\hyperbox-master\hyperbox\run.py", line 36, in main
    utils.print_config(config, resolve=True)
  File "D:\Codes\hyperbox-master\venv\lib\site-packages\pytorch_lightning\utilities\rank_zero.py", line 32, in wrapped_fn
    return fn(*args, **kwargs)
  File "D:\Codes\hyperbox-master\hyperbox\utils\utils.py", line 164, in print_config
    rich.print(tree, file=fp)
  File "D:\Codes\hyperbox-master\venv\lib\site-packages\rich\__init__.py", line 73, in print
    return write_console.print(*objects, sep=sep, end=end)
  File "D:\Codes\hyperbox-master\venv\lib\site-packages\rich\console.py", line 1694, in print
    self._buffer.extend(new_segments)
  File "D:\Codes\hyperbox-master\venv\lib\site-packages\rich\console.py", line 848, in __exit__
    self._exit_buffer()
  File "D:\Codes\hyperbox-master\venv\lib\site-packages\rich\console.py", line 806, in _exit_buffer
    self._check_buffer()
  File "D:\Codes\hyperbox-master\venv\lib\site-packages\rich\console.py", line 2009, in _check_buffer
    write(line)
  File "C:\Users\junai\miniconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2699' in position 0: character maps to <undefined>
*** You may need to add PYTHONIOENCODING=utf-8 to your environment ***

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

Process finished with exit code 1

**Comment by marsggbo** [comment]
Thanks for your question. It seems that something goes wrong with encoding. You can try:
1. `export PYTHONIOENCODING=UTF-8` before running your code
2. check whether your `config.yaml` contain any non-UTF-8 characters 
3. You can simply comment out line 36 of `D:\Codes\hyperbox-master\hyperbox\run.py`.  This line is used to print all your configurations, so removing it is fine.
