### ISSUE TITLE
Issue while running the code

### ISSUE THREAD

**Issue by ilhembekkr** [marsggbo/hyperbox#48]
Hello I am having issues while running hyperbox code, here an exemple, could you please help on how to fix it? 
```
commande:  python -m hyperbox.run experimen=example_random_nas trainer.fast_dev_run=True
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ibekkar/workplace/hyperbox/hyperbox/run.py", line 5, in <module>
    import hydra
  File "/opt/miniconda/envs/hyperbox/lib/python3.11/site-packages/hydra/__init__.py", line 5, in <module>
    from hydra import utils
  File "/opt/miniconda/envs/hyperbox/lib/python3.11/site-packages/hydra/utils.py", line 8, in <module>
    import hydra._internal.instantiate._instantiate2
  File "/opt/miniconda/envs/hyperbox/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 12, in <module>
    from hydra._internal.utils import _locate
  File "/opt/miniconda/envs/hyperbox/lib/python3.11/site-packages/hydra/_internal/utils.py", line 18, in <module>
    from hydra.core.utils import get_valid_filename, validate_config_path
  File "/opt/miniconda/envs/hyperbox/lib/python3.11/site-packages/hydra/core/utils.py", line 20, in <module>
    from hydra.core.hydra_config import HydraConfig
  File "/opt/miniconda/envs/hyperbox/lib/python3.11/site-packages/hydra/core/hydra_config.py", line 6, in <module>
    from hydra.conf import HydraConf
  File "/opt/miniconda/envs/hyperbox/lib/python3.11/site-packages/hydra/conf/__init__.py", line 46, in <module>
    class JobConf:
  File "/opt/miniconda/envs/hyperbox/lib/python3.11/site-packages/hydra/conf/__init__.py", line 75, in JobConf
    @dataclass
     ^^^^^^^^^
  File "/opt/miniconda/envs/hyperbox/lib/python3.11/dataclasses.py", line 1232, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/opt/miniconda/envs/hyperbox/lib/python3.11/dataclasses.py", line 1222, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda/envs/hyperbox/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda/envs/hyperbox/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'hydra.conf.JobConf.JobConfig.OverrideDirname'> for field override_dirname is not allowed: use default_factory
```

**Comment by marsggbo** [comment]
you can try to switch to a different version of hydra
